version: '2'

services:
    web:
        image: maxima-web
        build:
            context: .
            dockerfile: DockerfileWeb
        links:
            - maximatechdotnetchallenge-api-1
        ports:
            - "4200:80"
        networks:
            - maxima-network
        depends_on:
            - "api"

    api:
        image: maxima-api
        build:
            context: .
            dockerfile: DockerfileApi
        links:
            - maximatechdotnetchallenge-database-1
        ports:
            - "3000:5000"
        networks:
            - maxima-network
        depends_on:
            - "maxima-database"

networks:
    maxima-network:
        driver: bridge